// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void LightButtonPressed(lv_event_t * e)
{
	// Your code here
}

void CoopHeaterPressed(lv_event_t * e)
{
	// Your code here
}

void WaterheaterPressed(lv_event_t * e)
{
	// Your code here
}

void DoorPressed(lv_event_t * e)
{
	// Your code here
}
