// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_HomePage
void ui_HomePage_screen_init(void);
lv_obj_t *ui_HomePage;
lv_obj_t *ui_PageTitle;
void ui_event_LightButton( lv_event_t * e);
lv_obj_t *ui_LightButton;
lv_obj_t *ui_PageTitle1;
lv_obj_t *ui_LightImage;
lv_obj_t *ui_LightLabel;
void ui_event_CoopHeatButton( lv_event_t * e);
lv_obj_t *ui_CoopHeatButton;
lv_obj_t *ui_Image2;
lv_obj_t *ui_PageTitle2;
lv_obj_t *ui_CoopHeatLabel;
void ui_event_WaterHeatbutton( lv_event_t * e);
lv_obj_t *ui_WaterHeatbutton;
lv_obj_t *ui_Image3;
lv_obj_t *ui_PageTitle3;
lv_obj_t *ui_WaterHeatLabel;
lv_obj_t *ui_SettingsButton;
lv_obj_t *ui_DoorLabel1;
void ui_event_DoorButton( lv_event_t * e);
lv_obj_t *ui_DoorButton;
lv_obj_t *ui_Image4;
lv_obj_t *ui_PageTitle4;
lv_obj_t *ui_DoorLabel;
lv_obj_t *ui_InfoPanel;
lv_obj_t *ui_StatusTitle;
lv_obj_t *ui_StatusLabel;
lv_obj_t *ui_MacTitle;
lv_obj_t *ui_MacLabel;
lv_obj_t *ui_DayWeekTitle;
lv_obj_t *ui_DateTitle;
lv_obj_t *ui_TimeTitle;


// SCREEN: ui_SettingsPage
void ui_SettingsPage_screen_init(void);
lv_obj_t *ui_SettingsPage;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_[5] = {&ui_img_1_png, &ui_img_2_png, &ui_img_3_png, &ui_img_4_png, &ui_img_5_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_LightButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      LightButtonPressed( e );
}
}
void ui_event_CoopHeatButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      CoopHeaterPressed( e );
}
}
void ui_event_WaterHeatbutton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      WaterheaterPressed( e );
}
}
void ui_event_DoorButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      DoorPressed( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_HomePage_screen_init();
ui_SettingsPage_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_HomePage);
}
