// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_HomePage
void ui_HomePage_screen_init(void);
extern lv_obj_t *ui_HomePage;
extern lv_obj_t *ui_PageTitle;
void ui_event_LightButton( lv_event_t * e);
extern lv_obj_t *ui_LightButton;
extern lv_obj_t *ui_PageTitle1;
extern lv_obj_t *ui_LightImage;
extern lv_obj_t *ui_LightLabel;
void ui_event_CoopHeatButton( lv_event_t * e);
extern lv_obj_t *ui_CoopHeatButton;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_PageTitle2;
extern lv_obj_t *ui_CoopHeatLabel;
void ui_event_WaterHeatbutton( lv_event_t * e);
extern lv_obj_t *ui_WaterHeatbutton;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_PageTitle3;
extern lv_obj_t *ui_WaterHeatLabel;
extern lv_obj_t *ui_SettingsButton;
extern lv_obj_t *ui_DoorLabel1;
void ui_event_DoorButton( lv_event_t * e);
extern lv_obj_t *ui_DoorButton;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_PageTitle4;
extern lv_obj_t *ui_DoorLabel;
extern lv_obj_t *ui_InfoPanel;
extern lv_obj_t *ui_StatusTitle;
extern lv_obj_t *ui_StatusLabel;
extern lv_obj_t *ui_MacTitle;
extern lv_obj_t *ui_MacLabel;
extern lv_obj_t *ui_DayWeekTitle;
extern lv_obj_t *ui_DateTitle;
extern lv_obj_t *ui_TimeTitle;
// SCREEN: ui_SettingsPage
void ui_SettingsPage_screen_init(void);
extern lv_obj_t *ui_SettingsPage;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_2_png);   // assets/2.png
LV_IMG_DECLARE( ui_img_3_png);   // assets/3.png
LV_IMG_DECLARE( ui_img_4_png);   // assets/4.png
LV_IMG_DECLARE( ui_img_1_png);   // assets/1.png
LV_IMG_DECLARE( ui_img_5_png);   // assets/5.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
