// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_HomePage_screen_init(void)
{
ui_HomePage = lv_obj_create(NULL);
lv_obj_clear_flag( ui_HomePage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_HomePage, lv_color_hex(0x5024AB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HomePage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_HomePage, lv_color_hex(0x129F9F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_HomePage, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PageTitle = lv_label_create(ui_HomePage);
lv_obj_set_width( ui_PageTitle, 214);
lv_obj_set_height( ui_PageTitle, 44);
lv_obj_set_x( ui_PageTitle, 45 );
lv_obj_set_y( ui_PageTitle, 56 );
lv_label_set_text(ui_PageTitle,"Smart Coop");
lv_obj_set_style_text_color(ui_PageTitle, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PageTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PageTitle, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LightButton = lv_btn_create(ui_HomePage);
lv_obj_set_width( ui_LightButton, 288);
lv_obj_set_height( ui_LightButton, 126);
lv_obj_set_x( ui_LightButton, 308 );
lv_obj_set_y( ui_LightButton, 46 );
lv_obj_add_flag( ui_LightButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_LightButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_LightButton, 35, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LightButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LightButton, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LightButton, lv_color_hex(0x43AE20), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_LightButton, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_PageTitle1 = lv_label_create(ui_LightButton);
lv_obj_set_width( ui_PageTitle1, 214);
lv_obj_set_height( ui_PageTitle1, 44);
lv_obj_set_x( ui_PageTitle1, 27 );
lv_obj_set_y( ui_PageTitle1, -8 );
lv_obj_set_align( ui_PageTitle1, LV_ALIGN_CENTER );
lv_label_set_text(ui_PageTitle1,"Light");
lv_obj_set_style_text_color(ui_PageTitle1, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PageTitle1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_PageTitle1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PageTitle1, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LightImage = lv_img_create(ui_LightButton);
lv_img_set_src(ui_LightImage, &ui_img_2_png);
lv_obj_set_width( ui_LightImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LightImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LightImage, -86 );
lv_obj_set_y( ui_LightImage, 0 );
lv_obj_set_align( ui_LightImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LightImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_LightImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_LightImage, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_LightImage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LightLabel = lv_label_create(ui_LightButton);
lv_obj_set_width( ui_LightLabel, 147);
lv_obj_set_height( ui_LightLabel, 50);
lv_obj_set_x( ui_LightLabel, 25 );
lv_obj_set_y( ui_LightLabel, 49 );
lv_obj_set_align( ui_LightLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_LightLabel,"OFF");
lv_obj_set_style_text_color(ui_LightLabel, lv_color_hex(0x99E3FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LightLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LightLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LightLabel, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CoopHeatButton = lv_btn_create(ui_HomePage);
lv_obj_set_width( ui_CoopHeatButton, 288);
lv_obj_set_height( ui_CoopHeatButton, 126);
lv_obj_set_x( ui_CoopHeatButton, 308 );
lv_obj_set_y( ui_CoopHeatButton, 181 );
lv_obj_add_flag( ui_CoopHeatButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CoopHeatButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_CoopHeatButton, 35, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CoopHeatButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CoopHeatButton, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CoopHeatButton, lv_color_hex(0xDC910E), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_CoopHeatButton, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Image2 = lv_img_create(ui_CoopHeatButton);
lv_img_set_src(ui_Image2, &ui_img_3_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image2, -84 );
lv_obj_set_y( ui_Image2, 0 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_Image2, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PageTitle2 = lv_label_create(ui_CoopHeatButton);
lv_obj_set_width( ui_PageTitle2, 214);
lv_obj_set_height( ui_PageTitle2, 76);
lv_obj_set_x( ui_PageTitle2, 27 );
lv_obj_set_y( ui_PageTitle2, -16 );
lv_obj_set_align( ui_PageTitle2, LV_ALIGN_CENTER );
lv_label_set_text(ui_PageTitle2,"Coop\nHeater");
lv_obj_set_style_text_color(ui_PageTitle2, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PageTitle2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_PageTitle2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PageTitle2, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CoopHeatLabel = lv_label_create(ui_CoopHeatButton);
lv_obj_set_width( ui_CoopHeatLabel, 147);
lv_obj_set_height( ui_CoopHeatLabel, 50);
lv_obj_set_x( ui_CoopHeatLabel, 25 );
lv_obj_set_y( ui_CoopHeatLabel, 49 );
lv_obj_set_align( ui_CoopHeatLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CoopHeatLabel,"OFF");
lv_obj_set_style_text_color(ui_CoopHeatLabel, lv_color_hex(0x99E3FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CoopHeatLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CoopHeatLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CoopHeatLabel, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WaterHeatbutton = lv_btn_create(ui_HomePage);
lv_obj_set_width( ui_WaterHeatbutton, 288);
lv_obj_set_height( ui_WaterHeatbutton, 126);
lv_obj_set_x( ui_WaterHeatbutton, 308 );
lv_obj_set_y( ui_WaterHeatbutton, 317 );
lv_obj_add_flag( ui_WaterHeatbutton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_WaterHeatbutton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_WaterHeatbutton, 35, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_WaterHeatbutton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WaterHeatbutton, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_WaterHeatbutton, lv_color_hex(0xDC910E), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_WaterHeatbutton, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Image3 = lv_img_create(ui_WaterHeatbutton);
lv_img_set_src(ui_Image3, &ui_img_4_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image3, -86 );
lv_obj_set_y( ui_Image3, 0 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_Image3, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PageTitle3 = lv_label_create(ui_WaterHeatbutton);
lv_obj_set_width( ui_PageTitle3, 214);
lv_obj_set_height( ui_PageTitle3, 76);
lv_obj_set_x( ui_PageTitle3, 27 );
lv_obj_set_y( ui_PageTitle3, -14 );
lv_obj_set_align( ui_PageTitle3, LV_ALIGN_CENTER );
lv_label_set_text(ui_PageTitle3,"Water\nHeater");
lv_obj_set_style_text_color(ui_PageTitle3, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PageTitle3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_PageTitle3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PageTitle3, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WaterHeatLabel = lv_label_create(ui_WaterHeatbutton);
lv_obj_set_width( ui_WaterHeatLabel, 147);
lv_obj_set_height( ui_WaterHeatLabel, 50);
lv_obj_set_x( ui_WaterHeatLabel, 25 );
lv_obj_set_y( ui_WaterHeatLabel, 54 );
lv_obj_set_align( ui_WaterHeatLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_WaterHeatLabel,"OFF");
lv_obj_set_style_text_color(ui_WaterHeatLabel, lv_color_hex(0x99E3FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_WaterHeatLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_WaterHeatLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_WaterHeatLabel, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsButton = lv_btn_create(ui_HomePage);
lv_obj_set_width( ui_SettingsButton, 169);
lv_obj_set_height( ui_SettingsButton, 119);
lv_obj_set_x( ui_SettingsButton, 610 );
lv_obj_set_y( ui_SettingsButton, 325 );
lv_obj_add_flag( ui_SettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SettingsButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SettingsButton, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SettingsButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingsButton, 120, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DoorLabel1 = lv_label_create(ui_SettingsButton);
lv_obj_set_width( ui_DoorLabel1, 147);
lv_obj_set_height( ui_DoorLabel1, 50);
lv_obj_set_align( ui_DoorLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_DoorLabel1,"Advanced\nSettings");
lv_obj_set_style_text_color(ui_DoorLabel1, lv_color_hex(0x99E3FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DoorLabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DoorLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DoorLabel1, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DoorButton = lv_btn_create(ui_HomePage);
lv_obj_set_width( ui_DoorButton, 169);
lv_obj_set_height( ui_DoorButton, 271);
lv_obj_set_x( ui_DoorButton, 610 );
lv_obj_set_y( ui_DoorButton, 46 );
lv_obj_add_flag( ui_DoorButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_DoorButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_DoorButton, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_DoorButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DoorButton, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_DoorButton, lv_color_hex(0xAA6CE8), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_DoorButton, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Image4 = lv_img_create(ui_DoorButton);
lv_img_set_src(ui_Image4, &ui_img_1_png);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image4, 0 );
lv_obj_set_y( ui_Image4, 38 );
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_Image4, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PageTitle4 = lv_label_create(ui_DoorButton);
lv_obj_set_width( ui_PageTitle4, 214);
lv_obj_set_height( ui_PageTitle4, 76);
lv_obj_set_x( ui_PageTitle4, 0 );
lv_obj_set_y( ui_PageTitle4, -55 );
lv_obj_set_align( ui_PageTitle4, LV_ALIGN_CENTER );
lv_label_set_text(ui_PageTitle4,"Chicken\nDoor");
lv_obj_set_style_text_color(ui_PageTitle4, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PageTitle4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_PageTitle4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PageTitle4, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DoorLabel = lv_label_create(ui_DoorButton);
lv_obj_set_width( ui_DoorLabel, 147);
lv_obj_set_height( ui_DoorLabel, 50);
lv_obj_set_x( ui_DoorLabel, 0 );
lv_obj_set_y( ui_DoorLabel, 118 );
lv_obj_set_align( ui_DoorLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_DoorLabel,"Closed");
lv_obj_set_style_text_color(ui_DoorLabel, lv_color_hex(0x99E3FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DoorLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DoorLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DoorLabel, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InfoPanel = lv_obj_create(ui_HomePage);
lv_obj_set_width( ui_InfoPanel, 272);
lv_obj_set_height( ui_InfoPanel, 181);
lv_obj_set_x( ui_InfoPanel, 21 );
lv_obj_set_y( ui_InfoPanel, 116 );
lv_obj_clear_flag( ui_InfoPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_InfoPanel, 35, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_InfoPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_InfoPanel, 120, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_InfoPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StatusTitle = lv_label_create(ui_InfoPanel);
lv_obj_set_width( ui_StatusTitle, 214);
lv_obj_set_height( ui_StatusTitle, 44);
lv_obj_set_x( ui_StatusTitle, 5 );
lv_obj_set_y( ui_StatusTitle, 2 );
lv_label_set_text(ui_StatusTitle,"Device Status:");
lv_obj_set_style_text_color(ui_StatusTitle, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_StatusTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_StatusTitle, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StatusLabel = lv_label_create(ui_InfoPanel);
lv_obj_set_width( ui_StatusLabel, 147);
lv_obj_set_height( ui_StatusLabel, 50);
lv_obj_set_x( ui_StatusLabel, 55 );
lv_obj_set_y( ui_StatusLabel, -6 );
lv_obj_set_align( ui_StatusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_StatusLabel,"ONLINE");
lv_obj_set_style_text_color(ui_StatusLabel, lv_color_hex(0x99E3FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_StatusLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_StatusLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_StatusLabel, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MacTitle = lv_label_create(ui_InfoPanel);
lv_obj_set_width( ui_MacTitle, 214);
lv_obj_set_height( ui_MacTitle, 44);
lv_obj_set_x( ui_MacTitle, 5 );
lv_obj_set_y( ui_MacTitle, 75 );
lv_label_set_text(ui_MacTitle,"MAC Address:");
lv_obj_set_style_text_color(ui_MacTitle, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MacTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MacTitle, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MacLabel = lv_label_create(ui_InfoPanel);
lv_obj_set_width( ui_MacLabel, 147);
lv_obj_set_height( ui_MacLabel, 50);
lv_obj_set_x( ui_MacLabel, 55 );
lv_obj_set_y( ui_MacLabel, 67 );
lv_obj_set_align( ui_MacLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_MacLabel,"ONLINE");
lv_obj_set_style_text_color(ui_MacLabel, lv_color_hex(0x99E3FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MacLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MacLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MacLabel, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DayWeekTitle = lv_label_create(ui_HomePage);
lv_obj_set_width( ui_DayWeekTitle, 214);
lv_obj_set_height( ui_DayWeekTitle, 44);
lv_obj_set_x( ui_DayWeekTitle, 40 );
lv_obj_set_y( ui_DayWeekTitle, 307 );
lv_label_set_text(ui_DayWeekTitle,"Saturday");
lv_obj_set_style_text_color(ui_DayWeekTitle, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DayWeekTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DayWeekTitle, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DateTitle = lv_label_create(ui_HomePage);
lv_obj_set_width( ui_DateTitle, 324);
lv_obj_set_height( ui_DateTitle, 44);
lv_obj_set_x( ui_DateTitle, 40 );
lv_obj_set_y( ui_DateTitle, 347 );
lv_label_set_text(ui_DateTitle,"December 7, 2024");
lv_obj_set_style_text_color(ui_DateTitle, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DateTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DateTitle, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeTitle = lv_label_create(ui_HomePage);
lv_obj_set_width( ui_TimeTitle, 214);
lv_obj_set_height( ui_TimeTitle, 44);
lv_obj_set_x( ui_TimeTitle, 40 );
lv_obj_set_y( ui_TimeTitle, 390 );
lv_label_set_text(ui_TimeTitle,"5:59 PM");
lv_obj_set_style_text_color(ui_TimeTitle, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TimeTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TimeTitle, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_LightButton, ui_event_LightButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CoopHeatButton, ui_event_CoopHeatButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WaterHeatbutton, ui_event_WaterHeatbutton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_DoorButton, ui_event_DoorButton, LV_EVENT_ALL, NULL);

}
